# base image - node:alpine
FROM node:14.19.1-alpine

# set the working directory to /app
WORKDIR /app

# install ganache-cli globally
RUN npm install -g ganache-cli

# set the command ganache-cli -h 0.0.0.0 
# for docker ganache-cli host on 0.0.0.0
CMD ["ganache-cli","-h","0.0.0.0"]